config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :programs

  root 'home#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :muscle_group
  has_many :training_day_exercises
  has_many :training_days, :through => :training_day_exercises
  has_many :exercise_descriptions
  has_attached_file :ex_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :ex_image, content_type: /\Aimage\/.*\Z/
  def ex_image_url
    ex_image.url
  end
end

app/models/exercise_description.rb
class ExerciseDescription < ActiveRecord::Base
  belongs_to :exercise
  default_scope {order('id ASC')}
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
  has_many :exercises
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  def image_url
    image.url
  end
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :user
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :program_training_days
  has_many :training_days, :through => :program_training_days
  has_many :user_programs
  has_many :users, through: :user_programs

  TRAINING_TYPE = { :strength => 1, :mass => 2, :relief => 3}
  TRAINING_PLACE = {:gym => 1, :home => 2}

  PHYSICAL_LEVEL = {:low => 1,:middle => 2, :high => 3}
  MUSCLE_GROUP = {:back => 1, :chest => 2, :biceps => 3, :triceps => 4,
                  :shoulders => 5, :legs => 6, :press => 7}

end

app/models/program_training_day.rb
class ProgramTrainingDay < ActiveRecord::Base
  belongs_to :program
  belongs_to :training_day
end

app/models/training_day.rb
class TrainingDay < ActiveRecord::Base
  has_many :training_day_exercises
  has_many :exercises, :through => :training_day_exercises
  has_many :program_training_days
end

app/models/training_day_exercise.rb
class TrainingDayExercise < ActiveRecord::Base
  belongs_to :training_day
  belongs_to :exercise
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_programs
  has_many :programs, :through => :user_programs
  GENDER_OPTIONS = { :male => :true, :female => :false, :unspecified => :nil}
end

app/models/user_program.rb
class UserProgram < ActiveRecord::Base
  belongs_to :user
  belongs_to :program
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  EXCEPTIONS = [:created_at, :muscle_group_id, :exercise_id, :image, :ex_image]
  JSON_EX = {:include =>
                 {:exercise_descriptions =>
                      {:except => EXCEPTIONS + [:id]},
                  :muscle_group => {
                      except: EXCEPTIONS,
                      :methods => [:image_url]
                  }#,
                  #:training_day_exercises => {only: [:sets, :repetitions, :rest_time]}
                 },
             :except => EXCEPTIONS,
              :methods => [:ex_image_url]

  }
  JSON_DAY = {:include =>
                  {:exercises => JSON_EX
                  },
              :except => EXCEPTIONS}
  JSON_PROGRAM = {:include =>
                      {:training_days => JSON_DAY},
                  :except => EXCEPTIONS}
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
    respond_to do |format|
      format.html
      format.json { render :json => @exercises.to_json(JSON_EX) }
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @exercise.to_json(JSON_EX)}
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @groups = MuscleGroup.all
=begin
    @muscle_groups = MuscleGroup.all
    @ret = {}
    @muscle_groups.each {|group| @ret[group.name] = group.exercises}
    render json: @ret
=end
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  skip_before_action :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }

  def index
    @programs = Program.all
    respond_to do |format|
      format.html
      format.json { render :json => @programs.to_json(JSON_PROGRAM) }
    end
  end

  def show
    @program = Program.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @program.to_json(JSON_PROGRAM) }
    end
  end

  def new
    @program = Program.new
  end

  #post
  #post json
  self.allow_forgery_protection = false  # for curl purposes
  def create
    if params
      type = params[:program][:training_type].to_i
      place = params[:program][:training_place].to_i
      redirect_to program_path(Program.choose_program(type, place), :format => :json)
    end
  end

  def update

  end

  private
  def program_params
    params.require(:program).permit(:training_type, :training_place)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/exercises/show.html.erb
<h3><%= @exercise.name %></h3> (<%= @exercise.muscle_group.name %>)
<ol>
  <% @exercise.exercise_descriptions.each do |d|%>
    <li>
      <%= d.step %>
    </li>
  <% end %>
</ol>

app/views/home/index.html.erb
<% @groups.each do |g| %>
    <h3>
      <%= g.name %>
    </h3>
    <ul>
      <% g.exercises.each do |e|%>
        <h5>
          <%= e.name %>
        </h5>
          <ol>
            <% e.exercise_descriptions.each do |d| %>
                <li><em><%= d.step %></em></li>
            <% end %>
          </ol>
      <% end %>
    </ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalTrainer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/programs/index.html.erb
Programs
<ol>
  <% @programs.each do |p| %>
    <%= link_to 'Mass', program_path(p) %>
  <% end %>
</ol>

app/views/programs/new.html.erb
<%= form_for :program, url: programs_path do |f| %>
    <p>
      <%= f.label :gender %><br>
      <%= f.select :gender, Program::GENDER_OPTIONS  %>
    </p>
    <p>
      <%= f.label :age %><br>
      <%= f.text_field :age %>
    </p>

    <p>
      <%= f.label :weight %><br>
      <%= f.text_area :weight %>
    </p>
    <p>
      <%= f.label :height %><br>
      <%= f.text_area :height %>
    </p>
    <p>
      <%= f.label :activity %><br>
      <%= f.text_area :activity %>
    </p>
    <p>
      <%= f.label :physical_level %><br>
      <%= f.text_area :physical_level %>
    </p>
    <p>
    <%= f.label :complexity %><br>
    <%= f.text_area :complexity %>
    </p>
    <p>
      <%= f.label :training_type %><br>
      <%= f.select :training_type, Program::TRAINING_TYPE %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/programs/show.html.erb
<h3> Program </h3>
<% i = 1 %>
<% @program.training_days.each do |t| %>
    <strong>Day #<%= i%></strong>
    <ol>
      <% t.exercises.each do |ex|%>
        <li>
          <%= link_to ex.name, exercise_path(ex) %>
        </li>
      <% end %>
    </ol>

<% end %>